version: "3.8"

services:
  gateway:
    image: nginx:alpine
    ports:
      - "${TEAM_PORT:-8005}:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - team5_app
    networks:
      - app404

  team5_app:
    build:
      context: ../
      dockerfile: team5/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    expose:
      - "8000"
    environment:
      - DEBUG=1
    networks:
      - app404

networks:
  app404:
    external: true
    name: app404_net