version: '3.8'

services:
  team5_app:
    container_name: team5_container
    build:
      context: ../
      dockerfile: team5/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    ports:
      - "8005:8000"
    environment:
      - DEBUG=1
      - TEAM_APPS=team5